name: Setup Node and Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: |
          cd capstone_project/hello-world
          npm install
      - name: Run test
        run: |
          cd capstone_project/hello-world
          npm run test

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag capstone-project:$(date +%s)
